routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
});

// Route::get('/home', function () {
//     return view('home');
// });


// Admin Routes
//
Route::middleware(['auth', 'auth.isAdmin'])->prefix('admin')->name('admin.')->group(function () {
    Route::resource('/users', UserController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'msisdn',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // // mutator
    // public function setPasswordAttribute($password)
    // {
    //     $this->attributes['password'] = Hash::make($password);
    // }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function hasRole($roleId)
    {
        return in_array($roleId, $this->roles->pluck('id')->toArray());
    }
    
    /**
     * Check if user has a role
     *
     * @param  mixed $role
     * @return bool
     */
    public function hasAnyRole(string $role)
    {
        return null !== $this->roles()->where('name', $role)->first();
    }
    
    /**
     * Check if user has roles
     *
     * @param  mixed $role
     * @return bool
     */
    public function hasAnyRoles(array $role)
    {
        return null !== $this->roles()->whereIn('name', $role)->first();
    }

    // public function isMentor($mentee_id)
    // {
    //     return (bool)$this->mentor()->where('mentee_id', $mentee_id)->first(['id']);
    // }

    // public function mentor()
    // {
    //     return $this->hasMany(Mentor::class);
    // }

    // public function hasMentor(string $mentorID)
    // {
    //     return null !== $this->mentor()->whereIn('name', $role)->first();
    // }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Role;
use App\Models\User;
use App\Models\Mentee;
use App\Models\Mentor;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Requests\UserRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use App\Actions\Fortify\CreateNewUser;

class UserController extends Controller
{
    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {        
        if (Gate::denies('logged-in')) {
            dd('unauthorized');
        }
        $users = User::paginate(10);
        // dd($users);

        return view('admin.users.index')->with(
            [
                'users' => $users
            ]
        );
    } 

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create', [
            'roles' => Role::all(),
            'mentors' => Mentor::all(),
            'mentees' => Mentee::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        // dd($request);

        $newUser = new CreateNewUser();

        $user = $newUser->create(array_merge($request->only('first-name', 'last-name', 'email', 'password', 'password_confirmation'), ['msisdn' => null]));

        //Add mentor
        if (in_array('3', $request->roles)) {

            $mentor = Mentor::create([
                'first_name' => $user->first_name,
                'last_name' => $user->last_name,
                'user_id' => $user->id
            ]);

            if ($request->mentees) {
                $mentor->mentees()->sync($request->mentees);
            }
        } else if (in_array('4', $request->roles)) {

            $mentee = Mentee::create([
                'first_name' => $user->first_name,
                'last_name' => $user->last_name,
                'user_id' => $user->id,
                'mentor_id' => $request['mentor']
            ]);
        }

        $user->roles()->sync($request->roles);

        session()->flash('success', 'User Created Successfully!');

        return redirect(route('admin.users.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mentor = Mentor::where('user_id', $id)->first();
        $mentee = Mentee::where('user_id', $id)->first();

        if ($mentor) {
            return view(
                'admin.users.edit',
                [
                    'roles' => Role::all(),
                    'user' => User::find($id),
                    'mentor' => $mentor,
                ]
            );
        } else if ($mentee) {
            return view(
                'admin.users.edit',
                [
                    'roles' => Role::all(),
                    'user' => User::find($id),
                    'mentee' => $mentee,
                ]
            );
        }

        return view('admin.users.edit',
            [
                'roles' => Role::all(),
                'user' => User::find($id),
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findorFail($id);

        if (!$user) {
            session()->flash('failure', 'You cannot edit this user!');
            return redirect(route('admin.users.index'));
        }

        $data = $request->only(['first-name', 'last-name', 'email']);

        if ($request->roles) {
            $user->roles()->sync($request->roles);
        }

        $user->update($data);

        if (in_array('3', $request->roles)) {

            $mentor = Mentor::where('user_id', $id)->update([
                'first_name' => $request['first-name'],
                'last_name' => $request['last_name'],
            ]);

            if ($request->mentees) {
                $mentor->mentees()->sync($request->mentees);
            }
        } else if (in_array('4', $request->roles)) {
            Mentee::where('user_id', $id)->update([
                'first_name' => $request['first-name'],
                'last_name' => $request['last_name'],
                'mentor_id' => $request['mentor']
            ]);
        }

        session()->flash('success', 'User Updated Successfully!');

        return redirect(route('admin.users.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dd($id);
        User::destroy($id);

        session()->flash('success', 'User Deleted Successfully!');

        return redirect(route('admin.users.index'));
    }


}

resources/views/admin/users/create.blade.php
@extends('templates.main')

@section('css')

<!-- MULTI SELECT TOOL -SELECT2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<h1>Add User</h1>
<br>
<br>
<div class="card authform">
    <div class="card-body">
        <form method="POST" action="{{ route('admin.users.store') }}">
            @include('admin.users.partials.form')
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

<!-- MULTI SELECT TOOL -SELECT2 -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<script>
    $(document).ready(() => {
        $(".roles-selector").select2({
            tags: true
        });

        $('#role4').click(function() {
            console.log('a');
            if ($("#roles option[value=4]:selected").length > 0) {
                console.log('b');

                $('#mentorSection').attr('hidden', false);

            } else {

                $('#mentorSection').attr('hidden', true);

            }
        });

        $('#roles').on('change', function() {
            // var first = $(this).find('option').first().val();
            // var none = $(this).find('option:selected').length;
                        // $(this).val() == 4
            let selectObject = $('#roles').select2('data');

            let found = false;

            if (selectObject === undefined || selectObject.length == 0) {
                $('#mentorSection').attr('hidden', true);
            }

            for(var i = 0; i < selectObject.length; i++) {
                if (selectObject[i].text == 'Student') {
                    found = true;
                    $('#mentorSection').attr('hidden', false);
                    break;
                } else{
                    // console.log(found);
                    $('#mentorSection').attr('hidden', true);
                }
            }

            
        });
    });
</script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('templates.main')

@section('css')

<!-- MULTI SELECT TOOL -SELECT2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<h1>Edit User</h1>
<br>
<br>
<div class="card authform">
    <div class="card-body">
        <form method="POST" action="{{ route('admin.users.update', $user->id) }}">
            @method('PATCH')
            @include('admin.users.partials.form')
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>

<!-- MULTI SELECT TOOL -SELECT2 -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<script>
    $(document).ready(() => {
        $(".roles-selector").select2({
            tags: true
        });
    })
</script>
@endsection

resources/views/admin/users/index.blade.php
@extends('templates.main')

@section('content')

<div class="row">
    <div class="col-12">
        <h1 class="float-start">Users</h1>
        <a href="{{ route('admin.users.create') }}" class="btn btn-sm btn-success float-end" role="button">Add User</a>

    </div>
</div>

<div class="card">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">MSISDN</th>
                <th scope="col">Email</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <th scope="row">{{ $user->id }}</th>
                <td>{{ $user->first_name }}</td>
                <td>{{ $user->last_name }}</td>
                <td>{{ $user->msisdn }}</td>
                <td>{{ $user->email }}</td>
                <td scope="row">
                    <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-sm btn-primary" role="button">Edit</a>

                    <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" id="deleteUserForm{{ $user->id }}" class="float-end">
                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>

                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{ $users->links() }}
</div>
@endsection